In [ ]:
import numpy as np

In [2]:
import numpy as np
file=np.loadtxt("cric.tsv",skiprows=1)
file

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [3]:
import numpy as np
cric_data = np.loadtxt("cric_data.tsv",skiprows=1)
sachin=cric_data[:,1]
sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])

In [4]:
import numpy as np
cric_data = np.loadtxt("cric_data.tsv",skiprows=1)
Dravid=cric_data[:,2]
Dravid

array([ 78.,  62.,  85.,  24.,  17., 104.,  76.,  74.,  60.,  90.,   6.,
        69.,  65., 146., 110.])

In [5]:
import numpy as np
cric_data = np.loadtxt("cric_data.tsv",skiprows=1)
india=cric_data[:,3]
india

array([342., 191., 252., 307., 229., 246., 226., 288., 216., 304., 272.,
       302., 312., 370., 362.])

In [6]:
mean = np.mean(sachin)
mean

63.6

In [7]:
mean = np.mean(Dravid)
mean

71.06666666666666

In [9]:
mean = np.mean(india)
mean

281.26666666666665

In [10]:
max=np.max(sachin)
max

147.0

In [11]:
max=np.max(Dravid)
max

146.0

In [12]:
max=np.max(india)
max

370.0